#!/usr/bin/env bash

set -e

cd $(dirname $0)

source ./env

if [[ $# -eq 0 ]]; then
	set -- cmd/*
fi

version=$(git describe --dirty)
version="${version#v}"
version="${version/-/+}"
ldflags="-X ${REPO_PATH}/version.Version=${version}"

host_build() {
	local cmd="$(basename "${1}")"
	echo "Building host ${cmd}"

	if [[ "${GOHOSTARCH}" == "${GOARCH}" ]]; then
		install_dir="bin"
	else
		install_dir="bin/${GOARCH}"
	fi
	mkdir -p "${install_dir}"
	go build -ldflags "${ldflags}" -o "${install_dir}/${cmd}" "${REPO_PATH}/cmd/${cmd}"
}

cross_build() {
	local arch=${1}
	local cmd=${2}

	[[ -z "${NO_CROSS}" ]] || return 0

	echo "Building cross ${arch}/${cmd}"

	mkdir -p "bin/${arch}"
	CGO_ENABLED=0 GOARCH=${arch} \
		go build -ldflags "${ldflags}" \
		-o "bin/${arch}/${cmd}" "${REPO_PATH}/cmd/${cmd}"
}

for cmd in "$@"; do
	cmd=${cmd##cmd/}
	case "${cmd}" in
	amd64/kolet )
		cross_build amd64 kolet
		;;
	arm64/kolet )
		cross_build arm64 kolet
		;;
	*kolet )
		cross_build amd64 kolet
		cross_build arm64 kolet
		;;
	* )
		host_build "${cmd}"
		;;
	esac
done
